### ISSUE TITLE
Define Target Audience, Outcomes of the document

### ISSUE THREAD

**Issue by nrooney** [w3c-webmob/mobile_best_practices#16] opened 2014-01-22 15:46 UTC
We should define target audience, outcome of document and next steps once completed. Add this to README.md file.

**Comment by jorabin** [comment] 2014-01-22 16:29
This is a near duplicate of https://github.com/w3c-webmob/mobile_best_practices/issues/11

**Closed as completed** 2018-02-06 08:36 UTC
